CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_IDLE_STACK_SIZE=2048

CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="TEST_UART"
CONFIG_BT_DEVICE_APPEARANCE=833
CONFIG_BT_USER_PHY_UPDATE=n
CONFIG_BT_AUTO_PHY_UPDATE=n
CONFIG_BT_PHY_UPDATE=n

# # add #
CONFIG_BT_FIXED_PASSKEY=y
CONFIG_BT_BONDABLE=y

# CONFIG_BT_PRIVACY=y
CONFIG_BT_DIS=y
CONFIG_BT_BAS=y
CONFIG_BT_AUTO_DATA_LEN_UPDATE=n
CONFIG_BT_MAX_PAIRED=2
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y

CONFIG_BT_SETTINGS=y

# 
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

CONFIG_NVS=y
CONFIG_SETTINGS=y

# debug
CONFIG_BT_DEBUG_SMP=n
CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE=y
# # add #

CONFIG_BT_LL_PREEMPTED_TIME_FOR_ONE_MSEL=400

CONFIG_BT_SET_PUBLIC_MAC=y
CONFIG_BT_USER_DEFINED_PUBLIC_MAC=n
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_FLASH=y

CONFIG_GPIO=y

# # LowPower
# CONFIG_PM=y
# #Clock Source is RCL
# CONFIG_BT_CTLR_SLEEP_CLOCK_SOURCE=1
# #Accuracy is 1000ppm
# CONFIG_BT_CTLR_SLEEP_TIMER_ACCURACY=1000
# #Enable RCL Force CALIBRATION
# CONFIG_SOC_FORCE_CALIB_RCL_CLK=y

# Disable Serial Uart & Log.
# CONFIG_SERIAL=n
# CONFIG_UART_INTERRUPT_DRIVEN=n
# CONFIG_CONSOLE=n
# CONFIG_UART_CONSOLE=n
# CONFIG_PRINTK=n

# CONFIG_BT_DEBUG_CONN=n
# CONFIG_BT_DEBUG_LOG=n

#Enable DC/DC
CONFIG_SOC_DCDC_PAN1080=y
CONFIG_SOC_DCDC_DYNAMICALLY_TUNE_DRIVE_CAPABILITY=n

# CONFIG_BT_CTLR_EVENTS_PRIO=2

#Enbale link layer debug
# CONFIG_BT_CTLR_LINK_LAYER_DEBUG=y

# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=16
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=16
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=100

# Allow for large Bluetooth data packets.
CONFIG_BT_DATA_LENGTH_EXTENSION=y
CONFIG_BT_DATA_LENGTH_EXTENSION_VALUE=251
#实际发送的数据量是180，因为有三个是帧头
CONFIG_BT_L2CAP_TX_MTU=183  
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_GATT_CLIENT=y

CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME=y
CONFIG_REBOOT=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1480
CONFIG_ISR_STACK_SIZE=1500
CONFIG_BT_RX_STACK_SIZE=1500

######################  OTA CONFIG  ###########################
# Allow for large Bluetooth data packets.
CONFIG_BT_L2CAP_TX_MTU=252
CONFIG_BT_BUF_ACL_RX_SIZE=256

# Enable the Bluetooth (unauthenticated) and shell mcumgr transports.
CONFIG_MCUMGR_SMP_BT=y
CONFIG_MCUMGR_SMP_BT_AUTHEN=n

# Enable the LittleFS file system.
CONFIG_FILE_SYSTEM=n
CONFIG_FILE_SYSTEM_LITTLEFS=n

# Add 256 bytes to accommodate upload command (lfs_stat overflows)
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2304

# Enable mcumgr.
CONFIG_MCUMGR=y

# Ensure an MCUboot-compatible binary is generated.
CONFIG_BOOTLOADER_MCUBOOT=y

# Required by the `taskstat` command.
CONFIG_THREAD_MONITOR=n

# Enable statistics and statistic names.
CONFIG_STATS=n
CONFIG_STATS_NAMES=n

# Enable most core commands.
CONFIG_MCUMGR_CMD_IMG_MGMT=y
CONFIG_MCUMGR_CMD_OS_MGMT=n
CONFIG_MCUMGR_CMD_STAT_MGMT=n
###########################################################################